global:
  resolve_timeout: 5m
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: ${SMTP_FROM}
  smtp_auth_username: ${SMTP_FROM}
  smtp_auth_password: ${SMTP_PASSWORD}

route:
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: ${SMTP_TO_EMAIL}
        send_resolved: true
