name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
    paths:
      - 'api-stock360/services/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'api-stock360/services/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, users-service, requests-service, tools-service, warehouses-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./api-stock360/services/${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        working-directory: ./api-stock360/services/${{ matrix.service }}
        run: |
          pip install flake8
          flake8 . --max-line-length=120 
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker tag
        id: vars
        run: |
          TAG=$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then TAG="pr-${GITHUB_SHA::7}"; fi
          if [[ "${TAG}" == "main" ]]; then TAG="latest"; fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api-stock360/services/${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:${{ env.TAG }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest